defaults: &defaults
  background-color: "#FCFCFC"
  text-color: black
  header-glow: true
  header-glow-color: "#FF87FF"
  nav-text-color: black
  title: Omar Diab
  sections: [projects, experience, links, contact]

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
