common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: odiab
  password: 'testpass'

development:
  <<: *common
  database: omardiab_development

test:
  <<: *common
  database: omardiab_test

production:
  <<: *common
  database: omardiab_production

